# Generated by Django 5.0.4 on 2024-05-04 19:08

from django.db import migrations, models

# esta una migration creada de una tabla de una base de datos
class Migration(migrations.Migration):

    initial = True
# en dependencies se pones la relaciones 
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
